### ISSUE TITLE
run setup.sh error

### ISSUE THREAD

**Issue by cczaqq** [facebookresearch/mvfst-rl#38] opened 2022-03-22 05:28 UTC
Hello! Thank you for providing this highly integrated platform.
I tried to build the project in the conda environment with python 3.8 in Ubuntu 20.04LTS.
gcc version: 7.5.0
when I run ./setup.sh, the following error occurs:

g++ random.o memory.o memoryrange.o rat.o whisker.o whiskertree.o udp-socket.o traffic-generator.o remycc.o markoviancc.o estimators.o rtt-window.o sender.o protobufs-default/dna.pb.o -o sender -ljemalloc -lm -pthread -lprotobuf -lpthread -ljemalloc
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11WhiskerTreeE[_ZTVN11RemyBuffers11WhiskerTreeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11WhiskerTreeE[_ZTVN11RemyBuffers11WhiskerTreeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11MemoryRangeE[_ZTVN11RemyBuffers11MemoryRangeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11MemoryRangeE[_ZTVN11RemyBuffers11MemoryRangeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers6MemoryE[_ZTVN11RemyBuffers6MemoryE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers6MemoryE[_ZTVN11RemyBuffers6MemoryE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers7WhiskerE[_ZTVN11RemyBuffers7WhiskerE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers7WhiskerE[_ZTVN11RemyBuffers7WhiskerE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers19OptimizationSettingE[_ZTVN11RemyBuffers19OptimizationSettingE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers19OptimizationSettingE[_ZTVN11RemyBuffers19OptimizationSettingE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers20OptimizationSettingsE[_ZTVN11RemyBuffers20OptimizationSettingsE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers20OptimizationSettingsE[_ZTVN11RemyBuffers20OptimizationSettingsE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers5RangeE[_ZTVN11RemyBuffers5RangeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers5RangeE[_ZTVN11RemyBuffers5RangeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11ConfigRangeE[_ZTVN11RemyBuffers11ConfigRangeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11ConfigRangeE[_ZTVN11RemyBuffers11ConfigRangeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers9NetConfigE[_ZTVN11RemyBuffers9NetConfigE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers9NetConfigE[_ZTVN11RemyBuffers9NetConfigE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
makepp: error: Failed to build target `/home/jerry/project/mvfst-rl/mvfst-rl/_build/deps/pantheon/third_party/genericCC/sender' [1]
makepp: 17 files updated and 1 target failed
Traceback (most recent call last):
  File "/home/jerry/project/mvfst-rl/mvfst-rl/_build/deps/pantheon/src/wrappers/copa.py", line 53, in <module>
    main('do_ss:auto:0.5')
  File "/home/jerry/project/mvfst-rl/mvfst-rl/_build/deps/pantheon/src/wrappers/copa.py", line 29, in main
    check_call(['makepp', 'all', '--no-builtin-rules'], cwd=cc_repo)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['makepp', 'all', '--no-builtin-rules']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./src/experiments/setup.py", line 59, in <module>
    main()
  File "./src/experiments/setup.py", line 55, in main
    setup(args)
  File "./src/experiments/setup.py", line 45, in setup
    check_call([cc_src, 'setup'])
  File "/home/jerry/project/mvfst-rl/mvfst-rl/_build/deps/pantheon/src/helpers/subprocess_wrappers.py", line 24, in check_call
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/jerry/project/mvfst-rl/mvfst-rl/_build/deps/pantheon/src/wrappers/copa.py', 'setup']' returned non-zero exit status 1

It seems some google protobuf functions are not found, can you help me solve the problem?
Thanks a lot!

**Comment by odelalleau** [comment] 2022-03-22 12:59
Ok let's try. First make sure that you can reproduce the issue by running the following command from the `_build/deps/pantheon` folder:
```
rm -f third_party/genericCC/*.o && python2 ./src/experiments/setup.py --setup --schemes copa
```

Things you may try:
1. Run `conda list protobuf` and check that you get something like this:
```
# Name                    Version                   Build  Channel
libprotobuf               3.19.1               h4ff587b_0
protobuf                  3.19.1           py38h295c915_0
```
2. Make sure that the lib is indeed there with `ls -l $CONDA_PREFIX/lib/libprotobuf.so`
3. Make sure that the includes are indeed there with `ls $CONDA_PREFIX/include/google/protobuf`
4. Use gcc 9.3.0 (that's the version I'm using myself on Ubuntu 20.04)

**Comment by cczaqq** [comment] 2022-03-23 03:00
1.When I run "rm -f third_party/genericCC/*.o && python2 ./src/experiments/setup.py --setup --schemes copa", I can reproduce the issue.

2.When I run "conda list protobuf", I get this:
packages in environment at /home/jerry/anaconda3:

Name                    Version                   Build  Channel
libprotobuf               3.19.1               h4ff587b_0  
protobuf                  3.19.1           py39h295c915_0 

3.When I run "ls -l $CONDA_PREFIX/lib/libprotobuf.so", I get this:
/home/jerry/anaconda3/lib/libprotobuf.so -> libprotobuf.so.19.0.0

4.When I run "ls $CONDA_PREFIX/include/google/protobuf", I get this:
any.h                     extension_set.h                        map_entry.h           service.h
any.pb.h                  extension_set_inl.h                    map_entry_lite.h      source_context.pb.h
any.proto                 field_access_listener.h                map_field.h           source_context.proto
api.pb.h                  field_mask.pb.h                        map_field_inl.h       struct.pb.h
api.proto                 field_mask.proto                       map_field_lite.h      struct.proto
arena.h                   generated_enum_reflection.h            map.h                 stubs
arena_impl.h              generated_enum_util.h                  map_type_handler.h    text_format.h
arenastring.h             generated_message_bases.h              message.h             timestamp.pb.h
compiler                  generated_message_reflection.h         message_lite.h        timestamp.proto
descriptor_database.h     generated_message_table_driven.h       metadata.h            type.pb.h
descriptor.h              generated_message_table_driven_lite.h  metadata_lite.h       type.proto
descriptor.pb.h           generated_message_tctable_decl.h       parse_context.h       unknown_field_set.h
descriptor.proto          generated_message_tctable_impl.h       port_def.inc          util
duration.pb.h             generated_message_tctable_impl.inc     port.h                wire_format.h
duration.proto            generated_message_util.h               port_undef.inc        wire_format_lite.h
dynamic_message.h         has_bits.h                             reflection.h          wrappers.pb.h
empty.pb.h                implicit_weak_message.h                reflection_ops.h      wrappers.proto
empty.proto               inlined_string_field.h                 repeated_field.h
explicitly_constructed.h  io                                     repeated_ptr_field.h

5.Finally, I change GCC version from 7.5.0 to 9.4.0 which is installed by "apt install build-essential", and I still get the error. Should I change GCC version to 9.3.0, and try again, or are there other reasons? My Ubuntu version is 20.04.

Thank you!

**Comment by odelalleau** [comment] 2022-03-23 12:30
Alright, so at first sight everything looks good. I don't see any reason why gcc 9.3.0 would work better than 9.4.0 so don't bother with that. One unrelated detail is that your conda env seems to be with Python 3.9 but I've only tested the code with 3.8 (just an FYI, it has nothing to do with this error).

First thing first, my command was actually incomplete and wasn't cleaning up the protobuf files, so make sure to retry with gcc 9.4 and this command:
```
rm -f third_party/genericCC/*.o third_party/genericCC/protobufs-default/*.{h,cc,o} && python2 ./src/experiments/setup.py --setup --schemes copa
```

If it still doesn't work:
1. Make sure that running "git diff ba89258" in _build/deps/pantheon gives an empty result
2. Try to "force" it to use the correct protobuf library just to be 100% sure it's not a problem with that:
- Run `ln -s $CONDA_PREFIX/lib/libprotobuf.so $CONDA_PREFIX/lib/libprotobuftmp.so` to create a dummy "copy" of the library
- In folder `_build/deps/pantheon/third_party/genericCC` run the link command using that dummy copy:
```
LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH g++ random.o memory.o memoryrange.o rat.o whisker.o whiskertree.o udp-socket.o traffic-generator.o remycc.o markoviancc.o estimators.o rtt-window.o sender.o protobufs-default/dna.pb.o -o sender -ljemalloc -lm -pthread -lprotobuftmp -lpthread -ljemalloc
```
and see if it makes a difference

**Comment by cczaqq** [comment] 2022-03-24 01:45
1.When I run "rm -f third_party/genericCC/*.o third_party/genericCC/protobufs-default/*.{h,cc,o} && python2 ./src/experiments/setup.py --setup --schemes copa", it still does not work.
2.It is true that running "git diff ba89258" in _build/deps/pantheon gives an empty result.
3.When i run "ln -s $CONDA_PREFIX/lib/libprotobuf.so $CONDA_PREFIX/lib/libprotobuftmp.so" and "LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH g++ random.o memory.o memoryrange.o rat.o whisker.o whiskertree.o udp-socket.o traffic-generator.o remycc.o markoviancc.o estimators.o rtt-window.o sender.o protobufs-default/dna.pb.o -o sender -ljemalloc -lm -pthread -lprotobuftmp -lpthread -ljemalloc" according to your advice, I get the following error:

/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11WhiskerTreeE[_ZTVN11RemyBuffers11WhiskerTreeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11WhiskerTreeE[_ZTVN11RemyBuffers11WhiskerTreeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11MemoryRangeE[_ZTVN11RemyBuffers11MemoryRangeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11MemoryRangeE[_ZTVN11RemyBuffers11MemoryRangeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers6MemoryE[_ZTVN11RemyBuffers6MemoryE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers6MemoryE[_ZTVN11RemyBuffers6MemoryE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers7WhiskerE[_ZTVN11RemyBuffers7WhiskerE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers7WhiskerE[_ZTVN11RemyBuffers7WhiskerE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers19OptimizationSettingE[_ZTVN11RemyBuffers19OptimizationSettingE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers19OptimizationSettingE[_ZTVN11RemyBuffers19OptimizationSettingE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers20OptimizationSettingsE[_ZTVN11RemyBuffers20OptimizationSettingsE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers20OptimizationSettingsE[_ZTVN11RemyBuffers20OptimizationSettingsE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers5RangeE[_ZTVN11RemyBuffers5RangeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers5RangeE[_ZTVN11RemyBuffers5RangeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11ConfigRangeE[_ZTVN11RemyBuffers11ConfigRangeE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers11ConfigRangeE[_ZTVN11RemyBuffers11ConfigRangeE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers9NetConfigE[_ZTVN11RemyBuffers9NetConfigE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
/usr/bin/ld: protobufs-default/dna.pb.o:(.data.rel.ro._ZTVN11RemyBuffers9NetConfigE[_ZTVN11RemyBuffers9NetConfigE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status.

It seems no differences.

Thank you again!

**Comment by odelalleau** [comment] 2022-03-24 18:31
Well at least it confirms it's using the correct libprotobuf file :)

I only have a couple of suggestions left at this point:
1. Try a manual compilation to be sure it's not an issue with the Pantheon Python wrapper. From the `_build/deps/pantheon/third_party/genericCC` folder run:
```
rm -f *.o protobufs-default/*.{h,cc,o} && CPATH=$CONDA_PREFIX/include:$CPATH LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH makepp all --no-builtin-rules
```

2. Assuming the above fails (which is likely), try a full re-install from scratch (use --clean in setup.sh) in a fresh Python 3.8 conda env (in case it would be an issue with the Python 3.9 version of protobuf in conda)

**Comment by cczaqq** [comment] 2022-03-25 09:11
When I run a full re-install from scratch (use --clean in setup.sh) in a fresh Python 3.8 conda env, the problem is solved! 
I guess when I run "conda create -n mvfst-rl python=3.8 -y && conda activate mvfst-rl" for the first time, I am not in the su environment. This time I run "sudo su", and then run "conda create -n mvfst-rl python=3.8 -y && conda activate mvfst-rl".
Any way, thank you for your help!

**Comment by odelalleau** [comment] 2022-03-25 11:57
Hmm, this is weird, I don't really see why you would need to run `sudo su` first to create a new Python 3.8 env.
But as long as it works for you, great! => closing this issue

**Closed as completed by odelalleau** 2022-03-25 11:57 UTC
