### ISSUE TITLE
Issue with starting the pantheon network

### ISSUE THREAD

**Issue by Manjunathjogin** [facebookresearch/mvfst-rl#16] opened 2019-11-26 11:03 UTC
Hi @viswanathgs ,
I recently setup the mvfst-rl training environment and tried the training command and getting the below error in starting the pantheon env, with the test.py: error: unrecognized arguments: --extra-sender-args error.

python3 -m train.train --mode=train --base_logdir=/tmp/logs --total_steps=1  --learning_rate=0.00001 --num_actors=4 --cc_env_history_size=20 2>&1 | tee train_log.txt

i ave pasted the output log below.

/home/jogin/Desktop/mvfst-rl/train/utils.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg.read(), {"src_dir": SRC_DIR, "pantheon_root": PANTHEON_ROOT}
[INFO:31113 train:229 2019-11-24 17:24:47,653] Mode=train
[INFO:31113 train:167 2019-11-24 17:24:48,460] Starting agent 0 on device cpu. Mode=train, logdir=/tmp/logs/train
/home/jogin/Desktop/mvfst-rl/train/utils.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg.read(), {"src_dir": SRC_DIR, "pantheon_root": PANTHEON_ROOT}
[DEBUG:31125 cmd:728 2019-11-24 17:24:49,860] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jogin/Desktop/mvfst-rl, universal_newlines=False, shell=None, istream=<valid stream>)
/home/jogin/Desktop/mvfst-rl/train/utils.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg.read(), {"src_dir": SRC_DIR, "pantheon_root": PANTHEON_ROOT}
[INFO:31126 pantheon_env:359 2019-11-24 17:24:49,863] Using all 18 jobs.
[INFO:31126 pantheon_env:235 2019-11-24 17:24:49,866] Launching 18 jobs over 4 threads for train.
[DEBUG:31125 cmd:728 2019-11-24 17:24:49,867] Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/home/jogin/Desktop/mvfst-rl, universal_newlines=False, shell=None, istream=None)
[DEBUG:31125 cmd:728 2019-11-24 17:24:49,880] Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/home/jogin/Desktop/mvfst-rl, universal_newlines=False, shell=None, istream=None)
[INFO:31126 pantheon_env:277 2019-11-24 17:24:49,902] Located python2 in /usr/bin
[INFO:31126 pantheon_env:177 2019-11-24 17:24:49,904] Thread: 0, episode: 0, experiment: 15, cmd: /home/jogin/Desktop/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /tmp/logs/train/train_tid0_run0_expt15 --pkill-cleanup --uplink-trace /home/jogin/Desktop/mvfst-rl/train/traces/12mbps.trace --downlink-trace /home/jogin/Desktop/mvfst-rl/train/traces/12mbps.trace --prepend-mm-cmds mm-delay 30 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=bytes=30000 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_throughput_factor=1.0 --cc_env_reward_delay_factor=0.2 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_max_delay=True -v=1"
usage: test.py [-h] [-c CONFIG] {local,remote} ...
test.py: error: unrecognized arguments: --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_throughput_factor=1.0 --cc_env_reward_delay_factor=0.2 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_max_delay=True -v=1"
[INFO:31126 pantheon_env:177 2019-11-24 17:24:50,415] Thread: 0, episode: 1, experiment: 5, cmd: /home/jogin/Desktop/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /tmp/logs/train/train_tid0_run1_expt5 --pkill-cleanup --uplink-trace /home/jogin/Desktop/mvfst-rl/train/traces/114.68mbps.trace --downlink-trace /home/jogin/Desktop/mvfst-rl/train/traces/114.68mbps.trace --prepend-mm-cmds mm-delay 45 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=packets=450 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_throughput_factor=1.0 --cc_env_reward_delay_factor=0.2 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_max_delay=True -v=1"
Creating log directory: /tmp/logs/train/torchbeast/torchbeast-20191124-172449
[INFO:31125 file_writer:87 2019-11-24 17:24:50,828] Creating log directory: /tmp/logs/train/torchbeast/torchbeast-20191124-172449
Symlinked log directory: /tmp/logs/train/torchbeast/latest
[INFO:31125 file_writer:99 2019-11-24 17:24:50,829] Symlinked log directory: /tmp/logs/train/torchbeast/latest
Saving arguments to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/meta.json
[INFO:31125 file_writer:111 2019-11-24 17:24:50,829] Saving arguments to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/meta.json
Saving messages to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/out.log
[INFO:31125 file_writer:119 2019-11-24 17:24:50,834] Saving messages to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/out.log
Saving logs data to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/logs.csv
[INFO:31125 file_writer:129 2019-11-24 17:24:50,834] Saving logs data to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/logs.csv
Saving logs' fields to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/fields.csv
[INFO:31125 file_writer:130 2019-11-24 17:24:50,834] Saving logs' fields to /tmp/logs/train/torchbeast/torchbeast-20191124-172449/fields.csv
[INFO:31125 polybeast:437 2019-11-24 17:24:50,835] Not using CUDA.
[INFO:31126 pantheon_env:277 2019-11-24 17:24:50,910] Located python2 in /usr/bin
[INFO:31126 pantheon_env:177 2019-11-24 17:24:50,912] Thread: 1, episode: 0, experiment: 8, cmd: /home/jogin/Desktop/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /tmp/logs/train/train_tid1_run0_expt8 --pkill-cleanup --uplink-trace /home/jogin/Desktop/mvfst-rl/train/traces/108mbps.trace --downlink-trace /home/jogin/Desktop/mvfst-rl/train/traces/108mbps.trace --prepend-mm-cmds mm-delay 10 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=packets=1 --downlink-queue=droptail --downlink-queue-args=packets=1 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_throughput_factor=1.0 --cc_env_reward_delay_factor=0.2 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_max_delay=True -v=1"
usage: test.py [-h] [-c CONFIG] {local,remote} ...
test.py: error: unrecognized arguments: --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_throughput_factor=1.0 --cc_env_reward_delay_factor=0.2 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_max_delay=True -v=1"
[INFO:31126 pantheon_env:177 2019-11-24 17:24:51,243] Thread: 0, episode: 2, experiment: 9, cmd: /home/jogin/Desktop/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /tmp/logs/train/train_tid0_run2_expt9 --pkill-cleanup --uplink-trace /home/jogin/Desktop/mvfst-rl/train/traces/12mbps.trace --downlink-trace /home/jogin/Desktop/mvfst-rl/train/traces/12mbps.trace --prepend-mm-cmds mm-delay 50 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=packets=1 --downlink-queue=droptail --downlink-queue-args=packets=1 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_throughput_factor=1.0 --cc_env_reward_delay_factor=0.2 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_max_delay=True -v=1"
Server listening on unix:/tmp/rl_server_path_0
usage: test.py [-h] [-c CONFIG] {local,remote} ...
test.py: error: unrecognized arguments: --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_throughput_factor=1.0 --cc_env_reward_delay_factor=0.2 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_max_delay=True -v=1"

**Comment by viswanathgs** [comment] 2019-11-29 14:33
Hello @Manjunathjogin, thanks for reporting this. Could you make sure your panthoen setup is a fork of https://github.com/viswanathgs/pantheon instead of https://github.com/StanfordSNR/pantheon? This is the one that has the `--extra-sender-args` argument implemented in https://github.com/viswanathgs/pantheon/blob/master/src/experiments/arg_parser.py#L112. You can verify that by looking into pantheon code at _build/deps/pantheon.

**Comment by viswanathgs** [comment] 2019-11-29 14:35
Also, could you share the full versions of python2 and python3 in your setup?

**Comment by Manjunathjogin** [comment] 2019-11-30 16:09
Thanks for the response,
I forked the https://github.com/StanfordSNR/pantheon instead of https://github.com/viswanathgs/pantheon , I will correct that.

I am using python2.7.15 and python3.6.8 in my setup.

**Comment by viswanathgs** [comment] 2019-12-02 13:52
Okay yeah, the problem is then due to the pantheon repo. mvfst-rl relies on some minor changes to pantheon which we haven't merged upstream yet. Closing the issue given this, feel free to re-open if your problem persists.

**Closed by viswanathgs** 2019-12-02 13:52 UTC

**Comment by Manjunathjogin** [comment] 2019-12-04 10:00
Thanks, I was able to run the training script without any issues.

**Comment by Manjunathjogin** [comment] 2019-12-12 10:59
Hi @viswanathgs ,
I tried the below command for the training. I had query regarding  the number of episodes that will run during this command, from train/train.py  I could see that after the polybeast is done the pantheon env is killed, but in my case it was running eternally(Killed the script after 12 hours). Can you please help me in debugging this.

python3 -m train.train   --mode=train   --base_logdir=/tmp/logs   --total_steps=1   --learning_rate=0.00001   --num_actors=1  --cc_env_history_size=2 --max_jobs=1

Thanks,
